// <auto-generated />
namespace ONTO.Migrations.ONTOMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_UserProfileSettings_model3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_UserProfileSettings_model3));
        
        string IMigrationMetadata.Id
        {
            get { return "201802142254082_Added_UserProfileSettings_model3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
