// <auto-generated />
namespace ONTO.Migrations.ONTOMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PrateciList_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrateciList_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201801072042420_PrateciList_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
