// <auto-generated />
namespace ONTO.Migrations.ONTOMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changed_Name_Of_UserSettings_ModelTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changed_Name_Of_UserSettings_ModelTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802161145316_Changed_Name_Of_UserSettings_ModelTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
