// <auto-generated />
namespace ONTO.Migrations.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inital_create_identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inital_create_identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201803032056576_inital_create_identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
